##########################################################################
# this script was generated by openmm-builder. to customize it further,
# you can save the file to disk and edit it with your favorite editor.
##########################################################################

from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout

import argparse

def parse_args(args):
    parser = argparse.ArgumentParser()

    parser.add_argument("-c", "--checkpoint",
                        help="path to an OpenMM checkpoint",
                        type=str
                       )
    return parser.parse_args()

freq = int(1e5)
total = int(2e9)

pdb = app.PDBFile('input.pdb')
forcefield = app.ForceField('amber03.xml', 'amber03_obc.xml')

system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.NoCutoff,
     constraints=None)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 50/unit.picoseconds,
    1.0*unit.femtoseconds)

platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaDeviceIndex' : '0'}
simulation = app.Simulation(pdb.topology, system, integrator, platform, properties)
simulation.context.setPositions(pdb.positions)

simulation.reporters.append(app.DCDReporter('trajectory.dcd', freq))
simulation.reporters.append(app.StateDataReporter("sim.csv", freq, step=True,
    potentialEnergy=True, totalEnergy=True, temperature=True, separator='\t'))

simulation.reporters.append(app.CheckpointReporter('ckpt.chk', freq))

print('Running Production...')

total_steps = 0

while total_steps < total:
    simulation.step(freq)
    total_steps += freq
print('Done!')
